//! JSON Schema (draft 2020-12) target. Emits a single object schema
//! with one property per column. Properties are typed according to
//! the Arrow → JSON Schema mapping below; `additionalProperties` is
//! kept open (`true`) so a generated schema doesn't reject extra
//! fields a downstream system might add.
//!
//! Output is pretty-printed JSON via `serde_json::to_string_pretty` —
//! the preview pane shows it with syntax highlighting.

use serde_json::{Map, Value, json};

use crate::data::ColumnInfo;
use crate::data::schema_export::unknown_marker;

pub fn export(columns: &[ColumnInfo], table_name: &str) -> String {
    let title = table_name.to_string();
    let mut properties = Map::new();
    let mut required: Vec<Value> = Vec::new();

    for col in columns {
        properties.insert(col.name.clone(), property_for(&col.data_type));
        // Octa doesn't track nullability per column; treat every
        // column as required by default. Users can edit the output.
        required.push(Value::String(col.name.clone()));
    }

    let mut schema = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": title,
        "type": "object",
        "properties": Value::Object(properties),
        "required": required,
        "additionalProperties": true,
    });

    if let Value::Object(map) = &mut schema {
        map.insert(
            "$comment".to_string(),
            Value::String("Generated by octa — JSON Schema (draft 2020-12)".to_string()),
        );
    }

    serde_json::to_string_pretty(&schema).unwrap_or_else(|_| "{}".to_string()) + "\n"
}

fn property_for(data_type: &str) -> Value {
    match data_type {
        "Int8" | "Int16" | "Int32" | "Int64" | "UInt8" | "UInt16" | "UInt32" | "UInt64" => {
            json!({ "type": "integer" })
        }
        "Float16" | "Float32" | "Float64" => json!({ "type": "number" }),
        "Boolean" => json!({ "type": "boolean" }),
        "Utf8" | "LargeUtf8" | "String" => json!({ "type": "string" }),
        "Date32" | "Date64" => json!({ "type": "string", "format": "date" }),
        "Binary" | "LargeBinary" => {
            json!({ "type": "string", "contentEncoding": "base64" })
        }
        other => {
            if other.starts_with("Timestamp") {
                json!({ "type": "string", "format": "date-time" })
            } else {
                // Fall back to string with a note. Using "$comment" rather
                // than "description" so downstream tools that surface
                // descriptions to humans don't show implementation chatter.
                json!({
                    "type": "string",
                    "$comment": unknown_marker(other),
                })
            }
        }
    }
}
