//! Pydantic v2 target. Emits a `BaseModel` subclass with annotated
//! fields. Column names that aren't valid Python identifiers are
//! mapped to safe names + a `Field(..., alias=<original>)` so the
//! model still validates JSON that uses the original key.

use crate::data::ColumnInfo;
use crate::data::schema_export::{is_safe_ident, sanitize_ident, unknown_marker};

pub fn export(columns: &[ColumnInfo], table_name: &str) -> String {
    let class_name = to_class_name(table_name);
    let mut needs_date = false;
    let mut needs_datetime = false;
    let mut needs_field = false;
    let mut needs_optional_bytes = false;

    // Pass 1: figure out the import set.
    for col in columns {
        let (_, ty_kind) = pydantic_type(&col.data_type);
        match ty_kind {
            TypeKind::Date => needs_date = true,
            TypeKind::Datetime => needs_datetime = true,
            TypeKind::Bytes => needs_optional_bytes = true,
            TypeKind::Other => {}
        }
        if !is_safe_ident(&col.name) {
            needs_field = true;
        }
    }

    let mut out = String::new();
    out.push_str("# Generated by octa — Pydantic v2\n");
    let mut imports: Vec<&str> = Vec::new();
    if needs_field {
        imports.push("from pydantic import BaseModel, Field");
    } else {
        imports.push("from pydantic import BaseModel");
    }
    if needs_date || needs_datetime {
        let mut parts = Vec::new();
        if needs_date {
            parts.push("date");
        }
        if needs_datetime {
            parts.push("datetime");
        }
        let line = format!("from datetime import {}", parts.join(", "));
        out.push_str(&line);
        out.push('\n');
    }
    for i in imports {
        out.push_str(i);
        out.push('\n');
    }
    // `bytes` is a builtin; the dummy flag exists to silence the unused-
    // warning if we ever switch to `Optional[bytes]`. Keep the variable
    // for future extension but suppress the warning today.
    let _ = needs_optional_bytes;

    out.push('\n');
    out.push('\n');
    out.push_str(&format!("class {}(BaseModel):\n", class_name));
    if columns.is_empty() {
        out.push_str("    pass\n");
        return out;
    }

    for col in columns {
        let (py_type, _) = pydantic_type(&col.data_type);
        let safe = sanitize_ident(&col.name);
        let field_line = if is_safe_ident(&col.name) {
            format!("    {}: {}\n", safe, py_type)
        } else {
            // Pydantic requires the alias to be a string literal; embedded
            // quotes get escaped.
            let escaped = col.name.replace('\\', "\\\\").replace('"', "\\\"");
            format!(
                "    {}: {} = Field(..., alias=\"{}\")\n",
                safe, py_type, escaped
            )
        };
        out.push_str(&field_line);
    }
    out
}

fn to_class_name(table_name: &str) -> String {
    let cleaned = sanitize_ident(table_name);
    // PascalCase: split on _, capitalize each chunk.
    let mut s = String::with_capacity(cleaned.len());
    for chunk in cleaned.split('_').filter(|c| !c.is_empty()) {
        let mut chars = chunk.chars();
        if let Some(first) = chars.next() {
            for c in first.to_uppercase() {
                s.push(c);
            }
            for c in chars {
                s.push(c);
            }
        }
    }
    if s.is_empty() {
        "Row".to_string()
    } else if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        // Class names can't start with a digit.
        format!("Row_{}", s)
    } else {
        s
    }
}

enum TypeKind {
    Date,
    Datetime,
    Bytes,
    Other,
}

fn pydantic_type(data_type: &str) -> (String, TypeKind) {
    match data_type {
        "Int8" | "Int16" | "Int32" | "Int64" | "UInt8" | "UInt16" | "UInt32" | "UInt64" => {
            ("int".to_string(), TypeKind::Other)
        }
        "Float16" | "Float32" | "Float64" => ("float".to_string(), TypeKind::Other),
        "Boolean" => ("bool".to_string(), TypeKind::Other),
        "Utf8" | "LargeUtf8" | "String" => ("str".to_string(), TypeKind::Other),
        "Date32" | "Date64" => ("date".to_string(), TypeKind::Date),
        "Binary" | "LargeBinary" => ("bytes".to_string(), TypeKind::Bytes),
        other => {
            if other.starts_with("Timestamp") {
                ("datetime".to_string(), TypeKind::Datetime)
            } else {
                (format!("str  # {}", unknown_marker(other)), TypeKind::Other)
            }
        }
    }
}
