//! Rust struct target. Emits a `#[derive(Debug, Clone, Serialize,
//! Deserialize)]` struct with one field per column. Column names
//! that aren't valid Rust identifiers get sanitized + a
//! `#[serde(rename = "<original>")]` annotation so the struct still
//! round-trips JSON / CSV with the original field name.

use crate::data::ColumnInfo;
use crate::data::schema_export::{is_safe_ident, sanitize_ident, unknown_marker};

pub fn export(columns: &[ColumnInfo], table_name: &str) -> String {
    let struct_name = to_struct_name(table_name);
    let mut needs_chrono_date = false;
    let mut needs_chrono_datetime = false;

    // Pass 1: figure out the chrono import set.
    for col in columns {
        match rust_type(&col.data_type) {
            (_, TypeKind::Date) => needs_chrono_date = true,
            (_, TypeKind::Datetime) => needs_chrono_datetime = true,
            _ => {}
        }
    }

    let mut out = String::new();
    out.push_str("// Generated by octa - Rust struct\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");
    if needs_chrono_date || needs_chrono_datetime {
        let mut parts: Vec<&str> = Vec::new();
        if needs_chrono_date {
            parts.push("NaiveDate");
        }
        if needs_chrono_datetime {
            parts.push("NaiveDateTime");
        }
        out.push_str(&format!("use chrono::{{{}}};\n", parts.join(", ")));
    }
    out.push('\n');
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", struct_name));
    for col in columns {
        let (ty, _) = rust_type(&col.data_type);
        let safe = sanitize_ident(&col.name);
        if is_safe_ident(&col.name) {
            out.push_str(&format!("    pub {}: {},\n", safe, ty));
        } else {
            let escaped = col.name.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("    #[serde(rename = \"{}\")]\n", escaped));
            out.push_str(&format!("    pub {}: {},\n", safe, ty));
        }
    }
    if columns.is_empty() {
        // Empty struct still needs to be syntactically valid.
        out.push_str("    // (no columns)\n");
    }
    out.push_str("}\n");
    out
}

fn to_struct_name(table_name: &str) -> String {
    let cleaned = sanitize_ident(table_name);
    let mut s = String::with_capacity(cleaned.len());
    for chunk in cleaned.split('_').filter(|c| !c.is_empty()) {
        let mut chars = chunk.chars();
        if let Some(first) = chars.next() {
            for c in first.to_uppercase() {
                s.push(c);
            }
            for c in chars {
                s.push(c);
            }
        }
    }
    if s.is_empty() {
        "Row".to_string()
    } else if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Row_{}", s)
    } else {
        s
    }
}

enum TypeKind {
    Date,
    Datetime,
    Other,
}

fn rust_type(data_type: &str) -> (String, TypeKind) {
    match data_type {
        "Int8" => ("i8".to_string(), TypeKind::Other),
        "Int16" => ("i16".to_string(), TypeKind::Other),
        "Int32" => ("i32".to_string(), TypeKind::Other),
        "Int64" => ("i64".to_string(), TypeKind::Other),
        "UInt8" => ("u8".to_string(), TypeKind::Other),
        "UInt16" => ("u16".to_string(), TypeKind::Other),
        "UInt32" => ("u32".to_string(), TypeKind::Other),
        "UInt64" => ("u64".to_string(), TypeKind::Other),
        // f16 isn't in stable std; widen to f32. Document via comment so the
        // user can swap in `half::f16` themselves.
        "Float16" => (
            "f32 /* widened from Float16 */".to_string(),
            TypeKind::Other,
        ),
        "Float32" => ("f32".to_string(), TypeKind::Other),
        "Float64" => ("f64".to_string(), TypeKind::Other),
        "Boolean" => ("bool".to_string(), TypeKind::Other),
        "Utf8" | "LargeUtf8" | "String" => ("String".to_string(), TypeKind::Other),
        "Date32" | "Date64" => ("NaiveDate".to_string(), TypeKind::Date),
        "Binary" | "LargeBinary" => ("Vec<u8>".to_string(), TypeKind::Other),
        other => {
            if other.starts_with("Timestamp") {
                ("NaiveDateTime".to_string(), TypeKind::Datetime)
            } else {
                (
                    format!("String /* {} */", unknown_marker(other)),
                    TypeKind::Other,
                )
            }
        }
    }
}
