//! SQL DDL targets: Postgres, MySQL, SQLite, Databricks, Snowflake.
//! All produce a `CREATE TABLE` statement with one column per
//! `ColumnInfo`. The dialect tweaks come from two places: the
//! type-mapping table (`pg_type`, `mysql_type`, `sqlite_type`,
//! `databricks_type`, `snowflake_type`) and the identifier quoting
//! style (`"name"` for Postgres / SQLite / Snowflake, backticks for
//! MySQL / Databricks).
//!
//! Identifiers are emitted **bare** when they're already valid
//! (`[A-Za-z_][A-Za-z0-9_]*`) — the common case for real data, so the
//! DDL stays clean. Quoting only kicks in for names that genuinely
//! can't work bare: spaces, punctuation, or a leading digit.
//!
//! Octa doesn't track nullability per column today, so every column
//! is emitted without `NOT NULL`. If we ever add nullability metadata,
//! it lands here.

use crate::data::ColumnInfo;
use crate::data::schema_export::{is_safe_ident, sanitize_ident, unknown_marker};

pub fn export_postgres(columns: &[ColumnInfo], table_name: &str) -> String {
    build_create_table(columns, table_name, Dialect::Postgres)
}

pub fn export_mysql(columns: &[ColumnInfo], table_name: &str) -> String {
    build_create_table(columns, table_name, Dialect::Mysql)
}

pub fn export_sqlite(columns: &[ColumnInfo], table_name: &str) -> String {
    build_create_table(columns, table_name, Dialect::Sqlite)
}

pub fn export_databricks(columns: &[ColumnInfo], table_name: &str) -> String {
    build_create_table(columns, table_name, Dialect::Databricks)
}

pub fn export_snowflake(columns: &[ColumnInfo], table_name: &str) -> String {
    build_create_table(columns, table_name, Dialect::Snowflake)
}

#[derive(Debug, Clone, Copy)]
enum Dialect {
    Postgres,
    Mysql,
    Sqlite,
    Databricks,
    Snowflake,
}

impl Dialect {
    /// Render `ident` for use in DDL. An identifier that is already
    /// valid is emitted bare; one with spaces, punctuation, or a
    /// leading digit is wrapped in the dialect's quote characters,
    /// with the quote char itself escaped by doubling.
    fn quote_ident(self, ident: &str) -> String {
        if is_safe_ident(ident) {
            return ident.to_string();
        }
        match self {
            // Postgres / SQLite / Snowflake accept double-quoted
            // identifiers. Escape an embedded `"` as `""`.
            Dialect::Postgres | Dialect::Sqlite | Dialect::Snowflake => {
                format!("\"{}\"", ident.replace('"', "\"\""))
            }
            // MySQL and Databricks (Spark SQL) use backticks; embedded
            // ` becomes ``.
            Dialect::Mysql | Dialect::Databricks => {
                format!("`{}`", ident.replace('`', "``"))
            }
        }
    }

    fn map_type(self, data_type: &str) -> String {
        match self {
            Dialect::Postgres => pg_type(data_type),
            Dialect::Mysql => mysql_type(data_type),
            Dialect::Sqlite => sqlite_type(data_type),
            Dialect::Databricks => databricks_type(data_type),
            Dialect::Snowflake => snowflake_type(data_type),
        }
    }

    fn header_comment(self) -> &'static str {
        match self {
            Dialect::Postgres => "-- Generated by octa — Postgres dialect",
            Dialect::Mysql => "-- Generated by octa — MySQL dialect",
            Dialect::Sqlite => "-- Generated by octa — SQLite dialect",
            Dialect::Databricks => "-- Generated by octa — Databricks dialect",
            Dialect::Snowflake => "-- Generated by octa — Snowflake dialect",
        }
    }
}

fn build_create_table(columns: &[ColumnInfo], table_name: &str, dialect: Dialect) -> String {
    // `sanitize_ident` already coerces the table name to a valid
    // identifier, so it is always emitted bare.
    let table_ident = sanitize_ident(table_name);
    let mut out = String::new();
    out.push_str(dialect.header_comment());
    out.push('\n');
    out.push_str(&format!("CREATE TABLE {} (\n", table_ident));
    let last = columns.len().saturating_sub(1);
    for (idx, col) in columns.iter().enumerate() {
        let col_ident = dialect.quote_ident(&col.name);
        let col_type = dialect.map_type(&col.data_type);
        let comma = if idx == last { "" } else { "," };
        out.push_str(&format!("    {} {}{}\n", col_ident, col_type, comma));
    }
    out.push_str(");\n");
    out
}

fn pg_type(data_type: &str) -> String {
    match data_type {
        "Int8" | "Int16" => "SMALLINT".to_string(),
        "Int32" => "INTEGER".to_string(),
        "Int64" => "BIGINT".to_string(),
        // Postgres has no unsigned integer types — widen one bucket
        // and document the lift via the `unknown_marker` for UInt64
        // (which truly can't round-trip).
        "UInt8" => "SMALLINT".to_string(),
        "UInt16" => "INTEGER".to_string(),
        "UInt32" => "BIGINT".to_string(),
        "UInt64" => format!("NUMERIC(20, 0) /* {} (no unsigned in pg) */", data_type),
        "Float16" | "Float32" => "REAL".to_string(),
        "Float64" => "DOUBLE PRECISION".to_string(),
        "Boolean" => "BOOLEAN".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "TEXT".to_string(),
        "Date32" | "Date64" => "DATE".to_string(),
        "Binary" | "LargeBinary" => "BYTEA".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                // Postgres distinguishes between TIMESTAMP and TIMESTAMP WITH
                // TIME ZONE; Arrow's Timestamp has the same dichotomy via the
                // tz parameter ("Timestamp(Microsecond, Some(\"UTC\"))" vs
                // "...None"). Cheap check for "None" / "Some".
                if other.contains("None") {
                    "TIMESTAMP".to_string()
                } else {
                    "TIMESTAMPTZ".to_string()
                }
            } else {
                format!("TEXT /* {} */", unknown_marker(other))
            }
        }
    }
}

fn mysql_type(data_type: &str) -> String {
    match data_type {
        "Int8" => "TINYINT".to_string(),
        "Int16" => "SMALLINT".to_string(),
        "Int32" => "INT".to_string(),
        "Int64" => "BIGINT".to_string(),
        "UInt8" => "TINYINT UNSIGNED".to_string(),
        "UInt16" => "SMALLINT UNSIGNED".to_string(),
        "UInt32" => "INT UNSIGNED".to_string(),
        "UInt64" => "BIGINT UNSIGNED".to_string(),
        "Float16" | "Float32" => "FLOAT".to_string(),
        "Float64" => "DOUBLE".to_string(),
        // MySQL's BOOLEAN is an alias for TINYINT(1); use the alias
        // for readability.
        "Boolean" => "BOOLEAN".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "TEXT".to_string(),
        "Date32" | "Date64" => "DATE".to_string(),
        "Binary" => "BLOB".to_string(),
        "LargeBinary" => "LONGBLOB".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                "DATETIME".to_string()
            } else {
                format!("TEXT /* {} */", unknown_marker(other))
            }
        }
    }
}

fn sqlite_type(data_type: &str) -> String {
    // SQLite uses type *affinity*, not strict types — five buckets:
    // INTEGER / REAL / TEXT / BLOB / NUMERIC. We pick the closest
    // affinity for each Arrow type.
    match data_type {
        "Int8" | "Int16" | "Int32" | "Int64" | "UInt8" | "UInt16" | "UInt32" | "UInt64" => {
            "INTEGER".to_string()
        }
        "Float16" | "Float32" | "Float64" => "REAL".to_string(),
        // SQLite has no boolean type — store as 0/1 INTEGER.
        "Boolean" => "INTEGER".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "TEXT".to_string(),
        "Date32" | "Date64" => "TEXT".to_string(),
        "Binary" | "LargeBinary" => "BLOB".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                "TEXT".to_string()
            } else {
                format!("TEXT /* {} */", unknown_marker(other))
            }
        }
    }
}

fn databricks_type(data_type: &str) -> String {
    // Databricks SQL (Spark SQL / Delta Lake) type names.
    match data_type {
        "Int8" => "TINYINT".to_string(),
        "Int16" => "SMALLINT".to_string(),
        "Int32" => "INT".to_string(),
        "Int64" => "BIGINT".to_string(),
        // Spark SQL has no unsigned integer types — widen one bucket.
        // UInt64 can't round-trip; fall back to DECIMAL(20, 0).
        "UInt8" => "SMALLINT".to_string(),
        "UInt16" => "INT".to_string(),
        "UInt32" => "BIGINT".to_string(),
        "UInt64" => format!(
            "DECIMAL(20, 0) /* {} (no unsigned in Spark SQL) */",
            data_type
        ),
        "Float16" | "Float32" => "FLOAT".to_string(),
        "Float64" => "DOUBLE".to_string(),
        "Boolean" => "BOOLEAN".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "STRING".to_string(),
        "Date32" | "Date64" => "DATE".to_string(),
        "Binary" | "LargeBinary" => "BINARY".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                // TIMESTAMP is zoned (session tz); TIMESTAMP_NTZ is the
                // wall-clock type. Map the tz-less Arrow timestamp to
                // TIMESTAMP_NTZ, the zoned one to TIMESTAMP.
                if other.contains("None") {
                    "TIMESTAMP_NTZ".to_string()
                } else {
                    "TIMESTAMP".to_string()
                }
            } else {
                format!("STRING /* {} */", unknown_marker(other))
            }
        }
    }
}

fn snowflake_type(data_type: &str) -> String {
    // Snowflake's integer type names are all aliases of NUMBER(38, 0);
    // keep the readable spelling closest to the source width.
    match data_type {
        "Int8" => "TINYINT".to_string(),
        "Int16" => "SMALLINT".to_string(),
        "Int32" => "INTEGER".to_string(),
        "Int64" => "BIGINT".to_string(),
        // No unsigned types — widen one bucket; UInt64 can't round-trip.
        "UInt8" => "SMALLINT".to_string(),
        "UInt16" => "INTEGER".to_string(),
        "UInt32" => "BIGINT".to_string(),
        "UInt64" => format!(
            "NUMBER(20, 0) /* {} (no unsigned in Snowflake) */",
            data_type
        ),
        // Snowflake FLOAT / DOUBLE / REAL are all 64-bit IEEE doubles.
        "Float16" | "Float32" | "Float64" => "FLOAT".to_string(),
        "Boolean" => "BOOLEAN".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "VARCHAR".to_string(),
        "Date32" | "Date64" => "DATE".to_string(),
        "Binary" | "LargeBinary" => "BINARY".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                // TIMESTAMP_NTZ = no time zone, TIMESTAMP_TZ = tz-aware.
                if other.contains("None") {
                    "TIMESTAMP_NTZ".to_string()
                } else {
                    "TIMESTAMP_TZ".to_string()
                }
            } else {
                format!("VARCHAR /* {} */", unknown_marker(other))
            }
        }
    }
}
