//! TypeScript target. Emits an `interface` with one property per
//! column. Column names that aren't valid TS identifiers get
//! double-quoted property keys — TypeScript allows that.

use crate::data::ColumnInfo;
use crate::data::schema_export::{is_safe_ident, sanitize_ident, unknown_marker};

pub fn export(columns: &[ColumnInfo], table_name: &str) -> String {
    let interface_name = to_interface_name(table_name);
    let mut out = String::new();
    out.push_str("// Generated by octa — TypeScript interface\n");
    out.push_str(&format!("export interface {} {{\n", interface_name));
    for col in columns {
        let ts_type = ts_type(&col.data_type);
        let key = if is_safe_ident(&col.name) {
            col.name.clone()
        } else {
            // Quoted-property syntax; escape embedded quotes.
            format!(
                "\"{}\"",
                col.name.replace('\\', "\\\\").replace('"', "\\\"")
            )
        };
        out.push_str(&format!("  {}: {};\n", key, ts_type));
    }
    out.push_str("}\n");
    out
}

fn to_interface_name(table_name: &str) -> String {
    let cleaned = sanitize_ident(table_name);
    let mut s = String::with_capacity(cleaned.len());
    for chunk in cleaned.split('_').filter(|c| !c.is_empty()) {
        let mut chars = chunk.chars();
        if let Some(first) = chars.next() {
            for c in first.to_uppercase() {
                s.push(c);
            }
            for c in chars {
                s.push(c);
            }
        }
    }
    if s.is_empty() {
        "Row".to_string()
    } else if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Row_{}", s)
    } else {
        s
    }
}

fn ts_type(data_type: &str) -> String {
    match data_type {
        "Int8" | "Int16" | "Int32" | "Int64" | "UInt8" | "UInt16" | "UInt32" | "UInt64"
        | "Float16" | "Float32" | "Float64" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        "Utf8" | "LargeUtf8" | "String" => "string".to_string(),
        // Dates and timestamps cross the JSON boundary as ISO strings;
        // typing them as `string` matches the JSON Schema target and
        // common axios/fetch consumers. Callers that want `Date` can
        // post-process.
        "Date32" | "Date64" => "string /* ISO-8601 date */".to_string(),
        "Binary" | "LargeBinary" => "string /* base64 */".to_string(),
        other => {
            if other.starts_with("Timestamp") {
                "string /* ISO-8601 datetime */".to_string()
            } else {
                format!("string /* {} */", unknown_marker(other))
            }
        }
    }
}
